### ISSUE TITLE
Adafruit Feather M0 Express with samd21g18: Adafruit CircuitPython 5.3.1 and 6.0.0: MemoryError

### ISSUE THREAD

**Issue by GregoryBrandenbourger** [adafruit/Adafruit_CircuitPython_FONA#11]
Hi,

I followed the tutorial regarding circuit python with FONA 
https://learn.adafruit.com/cellular-data-for-circuitpython-with-fona/usage

Unfortunately, I have an error : memory allocation failed

Traceback (most recent call last):
File "code.py", line 6, in <module>
File "adafruit_requests.py", line 690, in <module>
MemoryError: memory allocation failed, allocating 184 bytes

**Comment by ladyada** [comment]
you'll need a chip with more memory, try M4 or nRF52 or STM32

**Comment by brentru** [comment]
Added warning at the top of the usage page of the guide referencing which types of chips are supported by this library to avoid future confusion.
