### ISSUE TITLE
Library overrides baudrate with 3G module

### ISSUE THREAD

**Issue by strau0106** [adafruit/Adafruit_CircuitPython_FONA#23]
Heyho, 

I bought a FONA 3G from adafruit a few days ago. I wanted to start using it but it did not work. It kept saying FONA not found. If I however directly sent AT commands witha a simple UART connection everything seemed to work fine. I did some additonal testing with debug=True in the __init__ and got weird unicode errors. After reviewing my connections and circuit twice or thrice I dove into the library code : ) To find the issue. In the fona_3g.py file on line 60 the library sets the baudrate to 4800. If I remove this line, my code now works. 

I would like to get your peoples opinion on it, and pending that I will submit a PR removing that line.

**Comment by tekktrik** [comment]
What is the baudrate you are using for your UART object that you're passing in as an argument?

**Comment by tekktrik** [comment]
Or are you just using `board.UART()`?
