### ISSUE TITLE
Bug when using adafruit_fona_network.CELLULAR

### ISSUE THREAD

**Issue by ric-sapasap** [adafruit/Adafruit_CircuitPython_FONA#24]
Hi, I'm using this FONA module (https://www.adafruit.com/product/1946) with a raspberry pico. I'm following the usage tutorial here: https://learn.adafruit.com/mqtt-in-circuitpython/circuitpython-cellular-usage. Unfortunately, it seems there's a bug when using the `CELLULAR` class in `adafruit_fona_network`. It is trying to enable GPS on the module, and the module doesn't support it. I've turned on debug logs on the library and here is what I got:
```
* Reset FONA
        UARTREAD ::
        UARTWRITE :: AT

        UARTREAD :: OK
        UARTREAD ::
        UARTWRITE :: ATE0

        UARTREAD :: OK
        UARTREAD ::
        UARTREAD ::
        UARTWRITE :: ATE0

        UARTREAD :: OK
        UARTREAD ::
        UARTWRITE :: AT+CVHU=0

        UARTREAD :: OK
        UARTWRITE :: ATI

        UARTREAD :: SIM800 R13.08

OK

Traceback (most recent call last):
  File "code.py", line 30, in <module>
  File "adafruit_fona/adafruit_fona_network.py", line 48, in __init__
  File "adafruit_fona/adafruit_fona.py", line 385, in gps
TypeError: GPS unsupported for this FONA module.
```

Line 30 in my code would be this:
```
network = network.CELLULAR(
    fona, (secrets["apn"], secrets["apn_username"], secrets["apn_password"])
)
```

I've also worked around this by doing the connection process without using the `CELLULAR` class, so I think the problem is there.

**Comment by tekktrik** [comment]
I don't believe GPS is supported for that product number, just cellular data.  You should reach out for support on the [Adafruit Customer Support Forums](https://forums.adafruit.com/) to confirm.

**Comment by tekktrik** [comment]
Yeah, I think this looks like a bug.  I think it doesn't know how to handle the response `SIM800 R13.08` and so doesn't behave properly.  I also think the logic check there isn't correct since it appears to always result in `True` anyways.

**Comment by ric-sapasap** [comment]
Hi, I'm actually interested if I can file a PR to fix this issue (and hopefully some other improvements). Can you point me to the documentation regarding contribution process? Thanks!
