### ISSUE TITLE
No module name 'Adafruit_fona'

### ISSUE THREAD

**Issue by docdamien** [adafruit/Adafruit_CircuitPython_FONA#9]
After following the steps outlined in the tutorials on the Adafruit site (installing blinka and the adafruit-circuitpython-fona packages with sudo pip3), when I run the example files, I get an error saying there is no module named 'Adafruit_fona'. 
When I reinstall them, it says all requirements are satisfied. Any ideas? I have the 808 board

**Comment by brentru** [comment]
Could you please run the following in your terminal:
`pip3 freeze | grep circuitpython` 

Copy and paste the output here.

**Comment by docdamien** [comment]
Here you go: 
```
adafruit-circuitpython-bmp280==3.2.3
adafruit-circuitpython-busdevice==5.0.1
adafruit-circuitpython-fona==2.1.0
adafruit-circuitpython-framebuf==1.4.3
adafruit-circuitpython-ssd1306==2.9.2
```

**Comment by docdamien** [comment]
Any news?

**Comment by ladyada** [comment]
post a screenshot of your error

**Comment by FoamyGuy** [comment]
Possibly the issue is with setup.py here: https://github.com/adafruit/Adafruit_CircuitPython_FONA/blob/0343cb590901c78af4f0510f25c63e4ef50d351f/setup.py#L52 looks like its set up for individual file instead of package so when installing it via pip perhaps not all files are present.

**Comment by brentru** [comment]
@FoamyGuy  That looks correct.

**Comment by brentru** [comment]
@docdamien We've updated this library (https://github.com/adafruit/Adafruit_CircuitPython_FONA/releases/tag/2.1.1).

Please re-install this library via: `pip3 install --upgrade --force-reinstall adafruit-circuitpython-fona`
